# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiaYFy_8ity-se9T6frqqWTtDL0BPTUV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def load_and_preprocess_data():
    raw_data = {
        'Book Title': [
            'A Light in the Attic', 'Tipping the Velvet', 'Soumission',
            'Sharp Objects', 'Sapiens', 'The Requiem Red',
            'The Dirty Little Secrets', 'The Coming Woman',
            'The Boys in the Boat', 'The Black Maria'
        ],
        'Price': [
            '£51.77', '£53.74', '£50.10', '£47.82', '£54.23',
            '£22.65', '£33.34', '£17.93', '£22.60', '£52.15'
        ],
        'Availability': ['In stock'] * 10
    }

    df = pd.DataFrame(raw_data)
    df['Clean_Price'] = df['Price'].str.replace('£', '').str.strip().astype(float)
    df['Price_Category'] = np.where(df['Clean_Price'] > 40.0, 'Premium Tier (> £40)', 'Economy Tier (≤ £40)')
    return df

def generate_visualizations(df):
    sns.set_theme(style="whitegrid", rc={"text.color": "#2c3e50", "axes.labelcolor": "#2c3e50"})

    fig, ax = plt.subplots(figsize=(11, 5.5))
    top_items = df.sort_values(by='Clean_Price', ascending=False).head(5)

    sns.barplot(
        x='Clean_Price',
        y='Book Title',
        data=top_items,
        ax=ax,
        palette='Blues_r',
        hue='Book Title',
        legend=False
    )

    for container in ax.containers:
        ax.bar_label(container, fmt='£%.2f', padding=8, fontweight='bold', color='#34495e')

    ax.set_title('Strategic Analysis: Top 5 Highest-Priced Asset Distributions', fontsize=15, fontweight='bold', pad=18)
    ax.set_xlabel('Unit Price Valuations (£)', fontsize=12, fontweight='semibold')
    ax.set_ylabel('Catalog Product Identifier', fontsize=12, fontweight='semibold')
    ax.set_xlim(0, max(top_items['Clean_Price']) * 1.15)

    sns.despine(left=True, bottom=True)
    plt.tight_layout()
    plt.savefig('top_expensive_books.png', dpi=300, bbox_inches='tight')
    plt.close()

    fig, ax = plt.subplots(figsize=(7, 7))
    segments = df['Price_Category'].value_counts()
    corporate_colors = ['#2b5c8f', '#74a9cf']

    wedges, texts, autotexts = ax.pie(
        segments,
        labels=segments.index,
        autopct='%1.1f%%',
        startangle=135,
        colors=corporate_colors,
        explode=(0.04, 0),
        shadow=False,
        textprops={"fontweight": "semibold", "fontsize": 11}
    )

    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_fontsize(11)

    ax.set_title('Inventory Composition: Value Class Distribution', fontsize=15, fontweight='bold', pad=18)
    plt.tight_layout()
    plt.savefig('catalog_segmentation_pie.png', dpi=300, bbox_inches='tight')
    plt.close()

if __name__ == "__main__":
    print("Initiating CodeAlpha Task 3 Pipeline...")
    try:
        processed_df = load_and_preprocess_data()
        generate_visualizations(processed_df)
        print("Execution Successful!")
        print("Target Visual Artifacts Written to Filesystem:")
        print("1. [IMAGE] -> 'top_expensive_books.png'")
        print("2. [IMAGE] -> 'catalog_segmentation_pie.png'")
    except Exception as e:
        print(f"Pipeline Interrupted: {str(e)}")